TITLE = 'Dungeon Squabble'

WINDOW_SIZE = (800, 600)
RES_SCALE = 0.5
DISPLAY_SIZE = (int(WINDOW_SIZE[0] * RES_SCALE), int(WINDOW_SIZE[1] * RES_SCALE))
#DISPLAY_SIZE = WINDOW_SIZE

TILE_SIZE = 20
HALF_TILE_SIZE = TILE_SIZE // 2

FPS = 30

DEBUG = True

MOUSE_BUTTON_RIGHT = 3